# Configuration for Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/

language: es

pipeline:
  - name: SpacyNLP
    model: es_core_news_sm
  - name: SpacyTokenizer
  - name: SpacyFeaturizer
    pooling: mean
  - name: LexicalSyntacticFeaturizer
  - name: CountVectorsFeaturizer
  - name: CountVectorsFeaturizer
    analyzer: char_wb
    min_ngram: 1
    max_ngram: 4
  - name: DIETClassifier
    epochs: 100
  - name: SpacyEntityExtractor

# Configuration for Rasa Core.
# https://rasa.com/docs/rasa/core/policies/
policies:
  - name: TEDPolicy
    epochs: 3
  - name: MemoizationPolicy
  - name: RulePolicy