# Configuration for Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/

language: es

pipeline:
  - name: SpacyNLP
    model: es_core_news_sm
  - name: SpacyTokenizer
  - name: SpacyFeaturizer
    pooling: mean
  - name: RegexFeaturizer
  - name: DIETClassifier
    entity_recognition: True
    epochs: 100

# Configuration for Rasa Core.
# https://rasa.com/docs/rasa/core/policies/
policies:
  - name: TEDPolicy
    epochs: 3
  - name: MemoizationPolicy
  - name: MappingPolicy
